.travis.ymllanguage: node_js
node_js: stable

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  on:
    branch: master

cache:
  directories:
  - node_modules

install:
- npm install

script:
- npm start
- cat src/data.js
- npm run build

branches:
  only:
  - master